[WIP] Re-factor CSS into multiple files and to support Post CSS Nesting
jupytercalpoly/jupyter-alabaster-theme pull request #61
Opened 2017-04-28 23:07 UTC by charnpreetsingh

2017-04-29 01:44 UTC, ellisonbg requested changes
Overall, looks good. The main thing is to make you have checked to make sure the generated CSS has all the rules from the hand written css files before.

2017-04-29 01:44 UTC, ellisonbg commented on jupyter_alabaster_theme/static/pcss/mobile_sidebar.pcss
> +    &-dropdown {
Wow, surprised this works in the middle of a sector. But looks like the CSS is what you would expect. Very cool!

2017-04-29 01:44 UTC, ellisonbg commented on jupyter_alabaster_theme/static/pcss/mobile_sidebar.pcss
> +      @nest &:hover {
Wouldn't `&:hover` work with no `@nest` in this case?

2017-04-29 01:44 UTC, ellisonbg commented on jupyter_alabaster_theme/static/pcss/navbar.pcss
> +    &-nav > li > &-active {
Does the double `&` work?

2017-05-01 20:25 UTC, charnpreetsingh commented on jupyter_alabaster_theme/static/pcss/mobile_sidebar.pcss
> +      @nest &:hover {
Good catch, I've changed that

2017-05-01 20:26 UTC, charnpreetsingh commented on jupyter_alabaster_theme/static/pcss/navbar.pcss
> +    &-nav > li > &-active {
Yep it does.

2017-05-01 20:28 UTC, ellisonbg commented on jupyter_alabaster_theme/static/pcss/navbar.pcss
> +    &-nav > li > &-active {
Very cool!

2017-05-01 22:36 UTC, ellisonbg approved these changes

2017-05-01 22:36 UTC, merged