User Docs Update
jupytercalpoly/jupyter-alabaster-theme pull request #74
Opened 2017-05-10 21:45 UTC by charnpreetsingh

Closes #72 

@willingc Please let me know what you think or a better way to word the instructions

2017-05-10 22:00 UTC, willingc requested changes
Double check that building without a theme specified in the `if not on_rtd` does in fact build with the new alabaster theme. It was not doing that when I worked with the theme and jupyterhub last week.

2017-05-10 22:00 UTC, willingc commented on docs/source/user.rst
> +   remove or modify it, otherwise ``sphinx_rtd_theme`` or the default readthedocs
edit the code block to select the desired theme to use for any local builds (such as during development):

*block to look for here*


If you are building documentation locally, you may specify a desired theme (jupyter_alabaster_theme) or the sphinx_rtd_theme:

*jupyter_alabaster theme* - use #72 code

*sphinx_rtd_theme - show example below.

2017-05-11 17:12 UTC, charnpreetsingh commented
@willingc  I verified that `jupyter_alabaster_theme`  does not need to be imported (via a clean conda environment) if developing locally.

2017-05-11 18:17 UTC, willingc approved these changes
Thanks @charnpreetsingh. Looking good :cake:

2017-05-11 18:17 UTC, merged